spring:
  application:
    name: medical
  jackson:
    time-zone: GMT+8
    default-property-inclusion: non_null
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bin_text?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 88888888
  servlet:
    multipart:
      max-file-size: 10MB
  web:
    resources:
      static-locations: classpath:/static/,file:./uploads/

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.qst.medical.domain

pagehelper:
  helper-dialect: mysql
  reasonable: true
  page-size-zero: true

upload:
  path: ./uploads/